<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <UseWindowsForms>true</UseWindowsForms>
    <Configurations>Debug;Release;DebugScene</Configurations>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugScene|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;DEBUGSCENE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Content\bin\**" />
    <Compile Remove="Content\obj\**" />
    <EmbeddedResource Remove="Content\bin\**" />
    <EmbeddedResource Remove="Content\obj\**" />
    <None Remove="Content\bin\**" />
    <None Remove="Content\obj\**" />
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.Xna.Framework.Content.ContentTypeReader" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.2.1105" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.2.1105" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </MonoGameContentReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenBound Game Launcher\OpenBound Game Launcher.csproj" />
    <ProjectReference Include="..\OpenBound Network Object Library\OpenBound Network Object Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ContentMetadata\Mobile\Aduka\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Armor\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\ASate\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Bigfoot\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\BlueWhale\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Boomer\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Dragon\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Frank\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Grub\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Ice\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\JD\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\JFrog\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Kalsiddon\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Knight\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Lightning\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Mage\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Maya\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Nak\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Phoenix\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Random\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\RaonLauncher\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Tiburon\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Trico\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Turtle\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ContentMetadata\Mobile\Wolf\RiderPivot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>