<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>OpenBound_Management_Tools</RootNamespace>
    <StartupObject>OpenBound_Management_Tools.Program</StartupObject>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBound Network Object Library\OpenBound Network Object Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DockerTemplates\OpenBound Database\OpenBoundDatabase.Template.Dockerfile">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DockerTemplates\OpenBound Database\OpenBoundDatabase.Template.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DockerTemplates\OpenBound Database\OpenBoundDatabase.Template.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Docker\Compose_build.py">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Docker\Compose_up.py">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DockerTemplates\FetchServer\OpenBoundFetchServer.nginx.Template.conf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DockerTemplates\FetchServer\OpenBoundFetchServer.Template.Dockerfile">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DockerTemplates\OpenBoundDatabaseServerCompose.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DockerTemplates\FetchServer\OpenBoundFetchServer.Template.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
